<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
$APPLICATION->SetTitle("TEST");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news.detail",
	"aboutSlide",
	Array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BROWSER_TITLE" => "-",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_CODE" => "",
		"ELEMENT_ID" => "375",
		"FIELD_CODE" => array("",""),
		"IBLOCK_ID" => "71",
		"IBLOCK_TYPE" => "about",
		"IBLOCK_URL" => "",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Страница",
		"PROPERTY_CODE" => array("NAME_ONE_SLIDE","NAME_TEN_SLIDE","NAME_ELEVEN_SLIDE","NAME_TWELVE_SLIDE","NAME_THIRTEEN_SLIDE","NAME_FOURTEEN_SLIDE","NAME_TWO_SLIDE","NAME_THREE_SLIDE","NAME_FOUR_SLIDE","NAME_FIVE_SLIDE","NAME_SIX_SLIDE","NAME_SEVEN_SLIDE","NAME_EIGHT_SLIDE","NAME_NINE_SLIDE","DESCRIPTION_ONE_SLIDE","DESCRIPTION_TEN_SLIDE","DESCRIPTION_ELEVEN_SLIDE","DESCRIPTION_TWELVE_SLIDE","DESCRIPTION_THIRTEEN_SLIDE","DESCRIPTION_FOURTEEN_SLIDE","DESCRIPTION_TWO_SLIDE","DESCRIPTION_THREE_SLIDE","DESCRIPTION_FOUR_SLIDE","DESCRIPTION_FIVE_SLIDE","DESCRIPTION_SIX_SLIDE","DESCRIPTION_SEVEN_SLIDE","DESCRIPTION_EIGHT_SLIDE","DESCRIPTION_NINE_SLIDE","FOUNDER",""),
		"SET_BROWSER_TITLE" => "N",
		"SET_CANONICAL_URL" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_SHARE" => "N"
	)
);?>
<div>
</div><?
//require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');
?>